In [4]:
import os
import math
import numpy as np
import time
import matplotlib.pyplot as plt
%matplotlib inline

from IPython.display import set_matplotlib_formats
set_matplotlib_formats("svg","pdf")
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

from tqdm.notebook import tqdm

In [6]:
import torch
print("Using torch",torch.__version__)

Using torch 1.7.1+cpu


In [8]:
torch.manual_seed(42)      

In [11]:
x = torch.Tensor(2,3,4)
print(x)
print(x.shape)
# tensor 생성시에 random값으로 생성

tensor([[[9.1837e-39, 4.6837e-39, 6.9796e-39, 9.0000e-39],
         [1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39],
         [9.8265e-39, 9.4592e-39, 1.0561e-38, 1.0653e-38]],

        [[1.0469e-38, 9.5510e-39, 8.7245e-39, 1.1020e-38],
         [8.7245e-39, 9.6429e-39, 9.6429e-39, 8.7245e-39],
         [4.2246e-39, 1.1112e-38, 9.6427e-39, 1.0561e-38]]])
torch.Size([2, 3, 4])


In [25]:
x = torch.Tensor([[1,2],[3,4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
x = torch.rand(2,3,4)
print(x)

tensor([[[0.5014, 0.3139, 0.4654, 0.1612],
         [0.1568, 0.2083, 0.3289, 0.1054],
         [0.9192, 0.4008, 0.9302, 0.6558]],

        [[0.0766, 0.8460, 0.3624, 0.3083],
         [0.0850, 0.0029, 0.6431, 0.3908],
         [0.6947, 0.0897, 0.8712, 0.1330]]])


In [27]:
shape = x.shape
print("shape:",x.shape)

size = x.size()
print("size:",size)

dim1,dim2,dim3 = x.size()
print("size:", dim1,dim2,dim3)

shape: torch.Size([2, 3, 4])
size: torch.Size([2, 3, 4])
size: 2 3 4


In [32]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)

y = x1+x2
print(x1,x2,y)

tensor([[0.8196, 0.9297, 0.4505],
        [0.3881, 0.5073, 0.4701]]) tensor([[0.6202, 0.6401, 0.0459],
        [0.3155, 0.9211, 0.6948]]) tensor([[1.4398, 1.5698, 0.4964],
        [0.7035, 1.4284, 1.1649]])


In [38]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)
x3 = torch.tensor([[1,2,3],[4,5,6]])

print("x1:(before):",x1)
print("x2:(before):",x2)
print("x3:(before):",x3)


x2.add_(x1)
x3.add(x1)
print("x1:(after):",x1)  
print("x2:(after):",x2)
print("x3:(after):",x3)

#x2.add(x1)이라는 명령어는 오류는 안나오는데 실질적으로 기능을 못하는 명령어



x1:(before): tensor([[0.4118, 0.2576, 0.3470],
        [0.0240, 0.7797, 0.1519]])
x2:(before): tensor([[0.7513, 0.7269, 0.8572],
        [0.1165, 0.8596, 0.2636]])
x3:(before): tensor([[1, 2, 3],
        [4, 5, 6]])
x1:(after): tensor([[0.4118, 0.2576, 0.3470],
        [0.0240, 0.7797, 0.1519]])
x2:(after): tensor([[1.1631, 0.9845, 1.2042],
        [0.1405, 1.6393, 0.4155]])
x3:(after): tensor([[1, 2, 3],
        [4, 5, 6]])


In [40]:
x = torch.arange(6)
print("x:",x)

x: tensor([0, 1, 2, 3, 4, 5])


In [42]:
x = x.view(2,3)
print("x:",x)

x: tensor([[0, 1, 2],
        [3, 4, 5]])


In [47]:
x = x.permute(1,0) #swaapping dimension 0 and 1 #  차원 축을 바꿔줌
print("X:",x)

X: tensor([[0, 1, 2],
        [3, 4, 5]])


In [49]:
x = torch.arange(6)
x = x.view(2,3)
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [51]:
w = torch.arange(9).view(3,3)
print(w)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [53]:
h = torch.matmul(x,w) # 일반적인 행렬곱
print(h)

tensor([[15, 18, 21],
        [42, 54, 66]])


In [84]:
x = torch.arange(12).view(3,4)
print("x",x)

x tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [85]:
print(x[1,:]) , print(x[1]) # 1행 출력
print(x[:,1]) # 1열 출력

tensor([4, 5, 6, 7])
tensor([4, 5, 6, 7])
tensor([1, 5, 9])


In [86]:
print(x[1:3,2:])

tensor([[ 6,  7],
        [10, 11]])


In [87]:
x = torch.ones((3,))
print(x.requires_grad)

False


In [88]:
x.requires_grad_(True)
print(x.requires_grad)

True


In [89]:
x = torch.arange(3,dtype=torch.float32,requires_grad=True)
print(x)

tensor([0., 1., 2.], requires_grad=True)


In [72]:
a = x + 2
b = a**2
c = b + 3
y = c.mean()
print(y)

tensor(12.6667, grad_fn=<MeanBackward0>)


In [73]:
y.backward()

In [74]:
print(x.grad)

tensor([2.6667, 4.0000, 5.3333])


In [76]:
gpu_avail = torch.cuda.is_available()
print(gpu_avail)

False


In [78]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device('cpu')
print(device)

cpu


In [80]:
x = torch.zeros(2,3)
x = x.to(device)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [81]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(42)
    torch.cuda.manual_seed_all(42)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False